site_name: Checkers
site_url: https://cryostem-tools.github.io/Checkers
nav:
  - Home: index.md
  - Install: install.md
  - User Guide: user_guide.md
  - Developers: developers.md
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
plugins:
  - search
  - mkdocs-homepage-copier
